#!/bin/sh

[ "${ACTION}" = "released" ] || exit 0

. /lib/functions.sh

logger "$BUTTON pressed for $SEEN seconds"

if [ "$SEEN" -gt 50 ]
then
	echo "FACTORY RESET" > /dev/console
	jffs2reset -y && reboot &
elif [ "$SEEN" -gt 4 ]
then
	/root/switch_internet.sh
fi

return 0
